server:
  port: 7003

eureka:
  instance:
    # eureka 服务端的实例名称
    hostname: localhost
  client:
    # 由于是注册中心，不能向自己进行注册自己
    register-with-eureka: false
    # 由于是注册中心，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 单机: 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

      # 集群时，配置其他机器信息（不包括自己的哦)
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7001/eureka/
